version: "3.7"
services:
  model_predictor_1:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    restart: no
    container_name: model_predictor1
    volumes:
      - ../../data/raw_data:/sample_solution/data/raw_data
      - ../../data/train_data:/sample_solution/data/train_data
      - ../../data/model_config:/sample_solution/data/model_config
      - ../../data/captured_data:/sample_solution/data/captured_data
    ports:
      - 3000:3000
    environment:
      MODEL_CONFIG_PATH: ${MODEL_CONFIG_PATH}
      MLFLOW_TRACKING_URI: http://172.17.0.1:5000/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    entrypoint: /bin/sh -c "python src/model_predictor.py --config-path ${MODEL_CONFIG_PATH} --port 3000"

  model_predictor_2:
    image: ${IMAGE_NAME}:${IMAGE_TAG} 
    restart: no
    container_name: model_predictor2
    volumes:
      - ../../data/raw_data:/sample_solution/data/raw_data
      - ../../data/train_data:/sample_solution/data/train_data
      - ../../data/model_config:/sample_solution/data/model_config
      - ../../data/captured_data:/sample_solution/data/captured_data
    ports:
      - 5040:5040
    environment:
      MODEL_CONFIG_PATH: ${MODEL_CONFIG_PATH}
      MLFLOW_TRACKING_URI: http://172.17.0.1:5000/
    entrypoint: /bin/sh -c "python src/model_predictor.py --config-path ${MODEL_CONFIG_PATH} --port 5040"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"

  gateway:
    image: nginx
    ports:
      - ${PORT}:80
    container_name: nginx
    restart: no
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
    - "host.docker.internal:host-gateway"
    command: 
      - bash
      - -c
      - 'nginx -g "daemon off;"'
    networks:
      - app-network
networks:
  app-network:
