version: "3.7"
services:
  mlflow:
    build:
      context: ../mlflow/mlflow/
    command:
      - bash
      - -c
      - "mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --serve-artifacts --host 0.0.0.0 --port 5000"
    ports:
      - 5000:5000
    expose:
      - "5000"
    volumes:
      - ../mlflow/run_env/data:/mlflow
      
  model_predictor_1:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    restart: no
    container_name: model_predictor1
    volumes:
      - ../../data/raw_data:/sample_solution/data/raw_data
      - ../../data/train_data:/sample_solution/data/train_data
      - ../../data/model_config:/sample_solution/data/model_config
      - ../../data/captured_data:/sample_solution/data/captured_data
    ports:
      - "3000"
    expose:
      - 3000
    environment:
      MODEL_CONFIG_PATH: ${MODEL_CONFIG_PATH}
      MLFLOW_TRACKING_URI: http://mlflow:5000/
    depends_on:
      - mlflow
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/sh -c "python src/model_predictor.py --config-path ${MODEL_CONFIG_PATH} --port 3000"

  model_predictor_2:
    image: ${IMAGE_NAME}:${IMAGE_TAG} 
    restart: no
    container_name: model_predictor2
    volumes:
      - ../../data/raw_data:/sample_solution/data/raw_data
      - ../../data/train_data:/sample_solution/data/train_data
      - ../../data/model_config:/sample_solution/data/model_config
      - ../../data/captured_data:/sample_solution/data/captured_data
    ports:
      - "5040"
    expose:
      - 5040
    environment:
      MODEL_CONFIG_PATH: ${MODEL_CONFIG_PATH}
      MLFLOW_TRACKING_URI: http://mlflow:5000/
    depends_on:
      - mlflow
    entrypoint: /bin/sh -c "python src/model_predictor.py --config-path ${MODEL_CONFIG_PATH} --port 5040"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway:
    image: nginx
    ports:
      - ${PORT}:80
    container_name: nginx
    restart: no
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
    - "host.docker.internal:host-gateway"
    command: 
      - bash
      - -c
      - 'nginx -g "daemon off;"'
    networks:
      - app-network
    depends_on:
      - mlflow
      - model_predictor_1
      - model_predictor_2

networks:
  app-network:
