version: '3.7'
services:
  gateway:
    image: nginx
    # ports:
    #   - 8080:80
    network_mode: "host"
    restart: no
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: 
      - bash
      - -c
      - 'nginx -g "daemon off;"'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"